meta_product_name: "TravelTribe"
meta_title: "TravelTribe - Make friends, save money, travel more."
meta_description: "Travel Tribe is a community where people can list, discover and book unique trip plans with friends or strangers all over the world online"
meta_image: "https://res.cloudinary.com/dhilged09/image/upload/v1647871071/production/OG-min_rt10ir.png" # should exist in `app/assets/images/`
